# Generated by Django 5.2.3 on 2025-08-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='active',
            new_name='status',
        ),
    ]
