# Generated by Django 5.2.3 on 2025-08-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchApp', '0002_rename_active_movie_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='streamingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('website', models.URLField(max_length=50)),
            ],
        ),
    ]
