# Generated by Django 5.2.3 on 2025-08-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchApp', '0003_streamingplatform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingplatform',
            name='website',
            field=models.CharField(max_length=50),
        ),
    ]
