# Generated by Django 5.2.3 on 2025-08-06 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchApp', '0005_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='streamingplatform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Streaming_Partner', to='watchApp.streamingplatform'),
        ),
    ]
