# Generated by Django 5.2.3 on 2025-08-06 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchApp', '0006_movie_streamingplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='movielist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reviews', to='watchApp.movie'),
        ),
    ]
