# Generated by Django 5.2.3 on 2025-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
