# Generated by Django 6.0.4 on 2026-04-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
                ('jersey_no', models.IntegerField(unique=True)),
                ('technical_skill', models.CharField(choices=[('batter', 'Batter'), ('bowler', 'Bowler'), ('ar', 'All-Rounder'), ('wk', 'Wicket Keeper'), ('c', 'Captain')], default='batter')),
                ('runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('status', models.CharField(default='Not Out', max_length=50)),
            ],
        ),
    ]
